# Site settings
name: Qoppa
version: 0.0.1
author: Max Quattromani
email: max@maxquattromani.com
description: ""
baseurl: ""
url: "http://qoppa.co"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-xxxxxxxx-x
jquery_version: 1.9.0

footer: "This is my footer"
