# Site settings
name: Qoppa
version: 0.0.1
author: Max Quattromani
email: max@maxquattromani.com
description: "A leading, Denver-based Web Design and Development Agency specializing in design, development, marketing, content creation, and graphic design."
baseurl: ""
url: "http://qoppa.co"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

footer: "This is our footer. Ain't it cool? Don't steal."

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-50387096-1
jquery_version: 1.9.0

sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
