# Site settings
name: Qoppa
version: 0.0.1
author: Max Quattromani
email: max@maxquattromani.com
description: "A leading, Denver-based Web Design and Development Agency with a combined 35 years of experience in design, development, marketing, content creation, and graphic design. Driven by a passion for combining art and technology; we create fantastic experiences for our customers and their users."
baseurl: ""
url: "http://qoppa.co"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-50387096-1
jquery_version: 1.9.0

footer: "This is our footer. Ain't it cool? Don't steal."
